apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: eks
  environments:
  - key: dev
    owner: mywork-v
    repository: Cluster
  - key: staging
  - key: production
  ingress:
    domain: 52.1.202.183.nip.io
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: bit7x
  repository: nexus
  secretStorage: vault
  vault: {}
  webhook: lighthouse
